version: '3'

services:
    server:
        image: ml-server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
        - 8000:8000 

    client:
        image: ml-client
        build: 
            context: ./client
            dockerfile: Dockerfile
        ports:
        - 8501:8501
